name: 'release dev container base-image'

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'src/base-image/**'
jobs:
  release-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get Ubuntu version
        id: ubuntu_version
        run: |
          UBUNTU_VERSION=$(grep -m 1 '^FROM' src/base-image/Dockerfile | awk -F ':' '{print $2}')
          echo "UBUNTU_VERSION=$UBUNTU_VERSION" >> $GITHUB_ENV
      - name: Extract metadata (tags, labels)
        id: extract_metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/ogis-rd/flexible-devcontainer/flexible-devcontainer
          tags: |
            type=semver, pattern=Ubuntu${{ env.UBUNTU_VERSION }}-{{version}}
            type=raw, value=Ubuntu${{ env.UBUNTU_VERSION }}-latest
          labels: |
            org.opencontainers.image.title=Flexible Dev Container
            org.opencontainers.image.description=Flexible Dev Container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/base-image
          push: true
          tags: ${{ steps.extract_metadata.outputs.tags }}
          labels: ${{ steps.extract_metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha, mode=max